function alignment_info = get_frame_times_imaging( ...
    imaging_base_path, sync_base_path, microscope_id, ...
    channel_number, plot_on)
%GET_FRAME_TIMES_IMAGING Detect imaging frame times from the slow-galvo signal.
%
% Inputs
%   imaging_base_path : Folder containing TSeries subfolders.
%   sync_base_path    : Folder containing matching .abf or .h5 sync files.
%   microscope_id     : Retained for compatibility ('2pplus' or 'investigator').
%   channel_number    : Sync channel containing the slow-galvo signal.
%   plot_on           : 0 for no plots, 1 for frame-detection QC plots.
%
% Output
%   alignment_info(acquisition_number).frame_times
%       Frame times in sync-sample units.
%
% Notes
%   - Assumes two imaging channels and counts Ch2 TIFF files.
%   - Assumes TSeries folders and sync files are returned in matching order.
%   - Long gaps in galvo peaks are filled using the estimated imaging rate,
%     preserving the original workflow for photostimulation-related gaps.

% Preserve unused input for compatibility with existing callers.
if nargin < 3
    microscope_id = [];
end

%% Locate synchronization files
if ~isempty(dir(fullfile(sync_base_path, '*.abf')))
    sync_dir = dir(fullfile(sync_base_path, '*.abf'));
    num_syncs = numel(sync_dir);
    is_pclamp = true;
else
    sync_dir = dir(fullfile(sync_base_path, '*.h5'));
    num_syncs = numel(sync_dir);
    is_pclamp = false;
end

%% Locate imaging acquisitions and verify counts
imaging_dir = dir(fullfile(imaging_base_path, '*TSeries*'));
num_tseries = numel(imaging_dir);

if num_syncs ~= num_tseries
    error( ...
        'Alignment:AcquisitionCountMismatch', ...
        ['Number of TSeries folders (%d) does not match ' ...
         'number of sync files (%d).'], ...
        num_tseries, num_syncs);
end

num_acqs = num_syncs;

%% Count TIFF frames for each TSeries
num_tifs = zeros(1, num_acqs);

for i = 1:num_acqs
    num_tifs(i) = numel(dir(fullfile( ...
        imaging_base_path, imaging_dir(i).name, '*Ch2*')));
end

%% Print the assumed imaging/sync pairing for visual verification
for acq_number = 1:num_acqs
    fprintf( ...
        'Acquisition %d: %s <-> %s\n', ...
        acq_number, ...
        imaging_dir(acq_number).name, ...
        sync_dir(acq_number).name);
end

alignment_info = struct([]);

%% Process each acquisition
for acq_number = 1:num_acqs
    expected_frame_count = num_tifs(acq_number);

    alignment_info(acq_number).imaging_id = ...
        imaging_dir(acq_number).name;

    alignment_info(acq_number).sync_id = ...
        sync_dir(acq_number).name;

    %% Load sync data and extract slow-galvo channel
    sync_file = fullfile( ...
        sync_base_path, sync_dir(acq_number).name);

    if is_pclamp
        [sync_data, sync_sampling_interval, header] = ...
            abfload(sync_file); %#ok<ASGLU>

        sync_sampling_rate = ...
            1 / sync_sampling_interval * 1e6;

        galvo_signal = sync_data(:, channel_number);

    else
        data = ws.loadDataFile(sync_file);
        fields = fieldnames(data);
        sweep_id = fields{2};
        sync_data = data.(sweep_id).analogScans;

        galvo_signal = sync_data(:, channel_number);
        sync_sampling_rate = ...
            data.header.AcquisitionSampleRate;
    end

    alignment_info(acq_number).sync_sampling_rate = ...
        sync_sampling_rate;

    %% Detect candidate frame peaks
    galvo_signal_norm = galvo_signal ./ max(galvo_signal);

    [~, frame_times] = findpeaks( ...
        galvo_signal_norm, ...
        'MinPeakHeight', 0.3, ...
        'MinPeakProminence', 0.1);

    if isempty(frame_times)
        error( ...
            'Alignment:NoFramePeaks', ...
            'No frame peaks were detected for acquisition %d.', ...
            acq_number);
    end

    %% Remove peaks with atypical scanning amplitude
    scanning_amplitude = ...
        mean(galvo_signal(frame_times));

    good_frame_times = find( ...
        galvo_signal(frame_times) < ...
            scanning_amplitude * 1.1 & ...
        galvo_signal(frame_times) > ...
            scanning_amplitude * 0.95);

    frame_times = frame_times(good_frame_times);
    initial_detected_frame_count = numel(frame_times);

    if numel(frame_times) < 2
        error( ...
            'Alignment:InsufficientFramePeaks', ...
            ['Fewer than two valid frame peaks were detected ' ...
             'for acquisition %d.'], ...
            acq_number);
    end

    %% Estimate imaging rate
    expected_interval = mode(diff(frame_times));

    imaging_frame_rate = ...
        1 / (expected_interval / sync_sampling_rate);

    frame_intervals_sec = ...
        diff(frame_times) .* (1 / sync_sampling_rate);

    frame_rate = round(1 ./ frame_intervals_sec); %#ok<NASGU>

    %% Optional QC plots
    if plot_on
        figure(87);
        clf;
        plot(galvo_signal);
        hold on;
        plot( ...
            frame_times, ...
            galvo_signal(frame_times), ...
            '*r');
        title('Galvo Signal and Defined Frame Times');
        set(gca, 'FontSize', 12);

        figure(88);
        clf;
        histogram(diff(frame_times));
        title( ...
            ['Unique frame intervals - if seeing a range of ' ...
             'values, check alignment carefully']);
        set(gca, 'FontSize', 12);
    end

    %% Fill long gaps caused by missing galvo movement during photostimulation
    long_intervals = find( ...
        diff(frame_times) > expected_interval * 1.5);

    long_intervals_for_bad_frames_calc = ...
        long_intervals;

    temp_bad_frames = [];

    if ~isempty(long_intervals)
        if plot_on
            figure(87);
            hold on;
            plot( ...
                frame_times(long_intervals), ...
                galvo_signal(frame_times(long_intervals)), ...
                '*c');
        end

        temp_frame_times = [];
        temp_frame_times(1:long_intervals(1)) = ...
            frame_times(1:long_intervals(1));

        for li = 1:numel(long_intervals)
            frame_intervals = [];

            last_good_frame_time = ...
                frame_times(long_intervals(li));

            next_good_frame_time = ...
                frame_times(long_intervals(li) + 1);

            num_frames_to_fill = round( ...
                (next_good_frame_time - last_good_frame_time) ...
                / sync_sampling_rate ...
                * imaging_frame_rate) - 1;

            if num_frames_to_fill > 0
                frame_intervals( ...
                    2:num_frames_to_fill + 1) = ...
                    1 / imaging_frame_rate ...
                    * sync_sampling_rate;

                frame_intervals(1) = ...
                    last_good_frame_time;

                fill_frame_times = ...
                    cumsum(frame_intervals);

                fill_frame_times = ...
                    fill_frame_times(2:end);
            else
                fill_frame_times = [];
            end

            temp_frame_times = cat( ...
                2, temp_frame_times, fill_frame_times);

            if li == numel(long_intervals)
                temp_frame_times = cat( ...
                    2, ...
                    temp_frame_times, ...
                    frame_times( ...
                        long_intervals(li) + 1:end)');
            else
                temp_frame_times = cat( ...
                    2, ...
                    temp_frame_times, ...
                    frame_times( ...
                        long_intervals(li) + 1: ...
                        long_intervals(li + 1))');
            end

            if num_frames_to_fill > 0
                new_bad_frames = ...
                    long_intervals_for_bad_frames_calc(li) + 1: ...
                    long_intervals_for_bad_frames_calc(li) ...
                    + num_frames_to_fill;

                temp_bad_frames = cat( ...
                    2, temp_bad_frames, new_bad_frames);

                long_intervals_for_bad_frames_calc(li:end) = ...
                    long_intervals_for_bad_frames_calc(li:end) ...
                    + num_frames_to_fill;
            end

            if plot_on && ~isempty(fill_frame_times)
                figure(87);
                plot( ...
                    fill_frame_times, ...
                    galvo_signal(fill_frame_times), ...
                    'ok');
                title( ...
                    ['Galvo Signal-Defined Plus Filled Frames ' ...
                     'During Photostimulations']);
            end
        end

        frame_times = temp_frame_times;
    end

    %% Match final count to the number of TIFF frames
    if numel(frame_times) > expected_frame_count
        frame_times = ...
            frame_times(1:expected_frame_count);
    end

    if numel(frame_times) < expected_frame_count
        warning( ...
            'Alignment:MissingFrames', ...
            ['Acquisition %d has fewer frame times than TIFFs: ' ...
             'detected %d, expected %d.'], ...
            acq_number, ...
            numel(frame_times), ...
            expected_frame_count);
    end

    final_frame_count = numel(frame_times);

    %% Store frame times and QC metadata
    alignment_info(acq_number).frame_times = ...
        frame_times;

    alignment_info(acq_number).bad_frames = ...
        temp_bad_frames;

    alignment_info(acq_number).qc.expected_frames = ...
        expected_frame_count;

    alignment_info(acq_number).qc.detected_frames_initial = ...
        initial_detected_frame_count;

    alignment_info(acq_number).qc.frames_final = ...
        final_frame_count;

    alignment_info(acq_number).qc.frame_count_difference = ...
        final_frame_count - expected_frame_count;

    alignment_info(acq_number).qc.frame_count_matches = ...
        final_frame_count == expected_frame_count;

    alignment_info(acq_number).qc.n_long_intervals = ...
        numel(long_intervals);

    alignment_info(acq_number).qc.n_filled_frames = ...
        numel(temp_bad_frames);

    fprintf( ...
        ['Acquisition %d: expected %d, initially detected %d, ' ...
         'final %d, filled %d.\n'], ...
        acq_number, ...
        expected_frame_count, ...
        initial_detected_frame_count, ...
        final_frame_count, ...
        numel(temp_bad_frames));
end
end
