%% run_multimodal_alignment.m
% Wrapper for task and passive multimodal alignment.
%
% Edit only the configuration block below for a new session. The processing
% logic remains unchanged from the original workflow, but paths, channels,
% thresholds, and run options are grouped and validated.

clearvars;
clc;

%% ------------------------------------------------------------------------
% 1. SESSION CONFIGURATION
% -------------------------------------------------------------------------
% Replace placeholder values below with local institutional paths and
% session-specific acquisition settings before running.
config.mouse = 'MOUSE_ID';
config.date = 'YYYY-MM-DD';
config.server = 'X:';
config.experimenter = 'EXPERIMENTER';
config.virmen_file_base = 'VIRMEN_FILE_BASE';

config.condition_file = fullfile( ...
    'PATH_TO_CONDITION_FILE', ...
    'condition_per_speaker.mat');

config.calibration_file = fullfile( ...
    'PATH_TO_CALIBRATION_FILE', ...
    'calibration_info.mat');

config.code_folder = fileparts(mfilename('fullpath'));

% config.mouse = 'KN8-3L';
% config.date = '2026-07-20';
% config.server = 'W:';
% config.experimenter = 'Connie';
% config.virmen_file_base = 'AGKN-8-3L_260720';
% 
% %running sensor calibration file path
% config.calibration_file = fullfile( ...
%     'V:', ...
%     'Connie', ...
%     'ball_calibration_summer2026_investigator', ...
%     'calibration_info.mat');
% 
% 
% % Code folder containing alignment helper functions
% config.code_folder = 'C:\Code\GitHub\Alternative_virmen_alignment';

%% ------------------------------------------------------------------------
% 2. ACQUISITION AND TASK/PASSIVE CONFIGURATION
% -------------------------------------------------------------------------

acquisition.galvo_channel = 6;
acquisition.virmen_channel = 5;
acquisition.vr_sync_string = 'VR';
acquisition.passive_sync_string = 'passive';

speaker.channel_numbers = [4, 7, 8];
speaker.ids = [1, 3, 2];
speaker.multiple_speakers_per_trial = true;

task.is_stim_dataset = true;
task.correct_iti_sec = 3;
task.incorrect_iti_sec = 5;
task.minimum_trial_duration_sec = 3.5;

passive_align_info.before_frames = 6;
passive_align_info.after_frames = 91;

%% ------------------------------------------------------------------------
% 3. SOUND-DETECTION CONFIGURATION
% -------------------------------------------------------------------------

task_sound.distance_between_sounds_sec = 2;
task_sound.distance_within_sounds_sec = 0.2;
task_sound.sound_duration_sec = 1;
task_sound.correct_iti_tone_sec = 0.250;
task_sound.incorrect_iti_tone_sec = 0.40;
task_sound.smoothing_factor = 15;
task_sound.detection_threshold = 3;
task_sound.unique_detection_threshold = [];
task_sound.corrected_iti = [];
task_sound.iti_tone_version = 2;

passive_sound.distance_between_sounds_sec = 2;
passive_sound.sound_duration_sec = 1;
passive_sound.smoothing_factor = 15;
passive_sound.detection_threshold = 4;
passive_sound.unique_detection_threshold = [];
passive_sound.sensor_change_date = datetime(2023, 7, 3);
passive_sound.distance_within_sounds_before_change_sec = 0.05;
passive_sound.distance_within_sounds_after_change_sec = 0.2;

%% ------------------------------------------------------------------------
% 4. RUN OPTIONS
% -------------------------------------------------------------------------

run_options.process_task = true;
run_options.process_passive = true;
run_options.recompute_alignment = false;
run_options.plot_task_alignment_qc = true;
run_options.interactive_qc = false;
run_options.calculate_velocity = true;
run_options.plot_velocity_qc = true;

%% ------------------------------------------------------------------------
% 5. BUILD PATHS AND LEGACY INFO STRUCTURES
% -------------------------------------------------------------------------

raw_root = fullfile( ...
    config.server, ...
    config.experimenter, ...
    'RawData', ...
    config.mouse,'/');

processed_root = fullfile( ...
    config.server, ...
    config.experimenter, ...
    'ProcessedData', ...
    config.mouse, ...
    config.date,'/');

info.mousename = config.mouse;
info.mouse = config.mouse;
info.date = config.date;
info.server = config.server;
info.experimenter_name = config.experimenter;

info.sync_base_path = fullfile( ...
    raw_root, 'wavesurfer', config.date,'/');

info.virmen_base = fullfile( ...
    raw_root, 'virmen', config.virmen_file_base);

info.imaging_base_path = fullfile( ...
    raw_root, config.date,'/');

info.processed_path = processed_root;
info.save_path = fullfile(processed_root, 'VR','/');

info.is_stim_dataset = task.is_stim_dataset;
info.galvo_channel = acquisition.galvo_channel;
info.virmen_channel = acquisition.virmen_channel;
info.vr_sync_string = acquisition.vr_sync_string;

sound_info = struct();
sound_info.spkr_channel_number = speaker.channel_numbers;
sound_info.speaker_ids = speaker.ids;
sound_info.mult_spkr = speaker.multiple_speakers_per_trial;
sound_info.interactive = run_options.interactive_qc;

task_info.correct = task.correct_iti_sec;
task_info.incorrect = task.incorrect_iti_sec;
task_info.min = task.minimum_trial_duration_sec;
task_info.channel_number = [ ...
    info.galvo_channel, ...
    info.virmen_channel, ...
    sound_info.spkr_channel_number];

%% ------------------------------------------------------------------------
% 6. VALIDATE CONFIGURATION AND LOAD SUPPORT FILES
% -------------------------------------------------------------------------

validate_configuration( ...
    config, info, sound_info);

addpath(genpath(config.code_folder));

condition_data = load(config.condition_file, ...
    'conditions_per_speaker');
conditions_per_speaker = ...
    condition_data.conditions_per_speaker;
sound_info.condition_per_speaker = ...
    conditions_per_speaker;

reward_pure = load(fullfile( ...
    config.reward_model_dir, 'mdl_pure_sol.mat'));
reward_end = load(fullfile( ...
    config.reward_model_dir, 'mdl_end_trial_sol.mat'));

mdl_pure_sol = reward_pure.mdl_pure_sol;
mdl_end_trial_sol = reward_end.mdl_end_trial_sol;

%% ------------------------------------------------------------------------
% 7. LOAD PROCESSED IMAGING DATA
% -------------------------------------------------------------------------

dff_data = load(fullfile( ...
    info.processed_path, 'dff.mat'), 'dff');
dff = dff_data.dff;

deconv_data = load(fullfile( ...
    info.processed_path, 'deconv', 'deconv.mat'), 'deconv');
deconv = deconv_data.deconv;

%% ------------------------------------------------------------------------
% 8. LOAD VIRMEN DATA
% -------------------------------------------------------------------------

[data, dataCell, virmen_source] = ...
    load_virmen_session(info.virmen_base);

fprintf( ...
    'Loaded ViRMEn source: %s\n', ...
    virmen_source);

fprintf( ...
    'Number of ViRMEn trials: %d\n', ...
    numel(dataCell.dataCell));

%% ------------------------------------------------------------------------
% 9. LOAD OR COMPUTE FRAME ALIGNMENT
% -------------------------------------------------------------------------

if ~isfolder(info.processed_path)
    mkdir(info.processed_path);
end

alignment_file = fullfile( ...
    info.processed_path, ...
    'alignment_info.mat');

if isfile(alignment_file) ...
        && ~run_options.recompute_alignment
    alignment_data = load( ...
        alignment_file, ...
        'alignment_info');
    alignment_info = alignment_data.alignment_info;
else
    alignment_info = get_frame_times_imaging( ...
        info.imaging_base_path, ...
        info.sync_base_path, ...
        [], ...
        info.galvo_channel, ...
        1);

    save( ...
        alignment_file, ...
        'alignment_info', ...
        '-v7.3');
end

% %% Calculate frame-aligned ball velocity

calibration_info = load(config.calibration_file).calibration_info;
if ~isfile(calibration_file)
    error( ...
        'Alignment:MissingCalibrationFile', ...
        'Calibration file not found: %s', ...
        calibration_file);
end

if run_options.calculate_velocity
    [raw_velocity, corrected_velocity, velocity_qc] = ...
        run_velocity_alignment( ...
            alignment_info, ...
            calibration_info, ...
            info.sync_base_path, ...
            info.processed_path, ...
            run_options.plot_velocity_qc);
end

%% ------------------------------------------------------------------------
% 10. PROCESS TASK DATA
% -------------------------------------------------------------------------

if run_options.process_task
    sound_info = apply_task_sound_config( ...
        sound_info, ...
        task_sound, ...
        alignment_info);

    %process sound inputs
    [sound_st, sound_trials, sound_condition_array] = ...
        find_spkr_output_task_simple( ...
            info, ...
            alignment_info, ...
            info.vr_sync_string, ...
            sound_info, ...
            sound_info.iti_tone_version);

    trial_info = build_trial_info( ...
        dataCell, ...
        info.is_stim_dataset);

    %get virmen trial iterations
    digidata_its = get_digidata_iterations( ...
        info.sync_base_path, ...
        info.vr_sync_string, ...
        info.virmen_channel, ...
        alignment_info);

    %find positive peaks in virmen to use for alignment
    [virmen_it, trial_its, sound_condition_array] = ...
        get_virmen_iterations_and_times_digidata_positive_peaks_simple( ...
            info.sync_base_path, ...
            info.virmen_channel, ...
            info.vr_sync_string, ...
            sound_condition_array, ...
            data, ...
            alignment_info);

    [vr_sound_frames, new_sound_st, sounds_per_file] = ...
        binarize_passive_sounds( ...
            sound_st, ...
            sound_info, ...
            alignment_info, ...
            'dir_string', ...
            info.vr_sync_string);

    % Reward-event detection is not enabled in this wrapper.
    reward_loc_pure_frames = [];

    %use all the data to create a imaging dictionary with trialized data
    imaging = align_virmen_data( ...
        dff, ...
        deconv, ...
        virmen_it, ...
        alignment_info, ...
        data, ...
        dataCell, ...
        trial_its, ...
        sounds_per_file, ...
        reward_loc_pure_frames);

    if run_options.plot_task_alignment_qc
        selected_fields = [1, 6, 7];
        plot_random_trials_alignment( ...
            imaging, ...
            selected_fields);
    end

    if ~isfolder(info.save_path)
        mkdir(info.save_path);
    end

    save( ...
        fullfile(info.save_path, ...
        'alignment_variables.mat'), ...
        'task_info', ...
        'sound_info', ...
        'sounds_per_file', ...
        'virmen_it', ...
        'sound_st', ...
        'new_sound_st', ...
        'sound_trials', ...
        'sound_condition_array', ...
        'reward_loc_pure_frames', ...
        'trial_its', ...
        'digidata_its', ...
        'trial_info', ...
        'info', ...
        '-v7.3');

    save( ...
        fullfile(info.save_path, 'imaging.mat'), ...
        'imaging', ...
        '-v7.3');

    save( ...
        fullfile(info.save_path, ...
        'vr_sound_frames.mat'), ...
        'vr_sound_frames', ...
        '-v7.3');

    vr_sound_frames_updated = ...
        fix_vr_sound_frames( ...
            vr_sound_frames, ...
            imaging, ...
            alignment_info);

    save( ...
        fullfile(info.save_path, ...
        'vr_sound_frames_updated.mat'), ...
        'vr_sound_frames_updated', ...
        '-v7.3');
end

%% ------------------------------------------------------------------------
% 11. PROCESS PASSIVE DATA
% -------------------------------------------------------------------------

if run_options.process_passive
    passive_info = info;
    passive_info.save_path = fullfile( ...
        info.processed_path, ...
        'passive');

    passive_sound_info = sound_info;
    passive_sound_info.interactive = ...
    run_options.interactive_qc;
    passive_sound_info = apply_passive_sound_config( ...
        passive_sound_info, ...
        passive_sound, ...
        alignment_info, ...
        config.date);

    [passive_sound_st, ...
        passive_sound_trials, ...
        passive_sound_condition_array] = ...
        find_spkr_output_task_simple( ...
            passive_info, ...
            alignment_info, ...
            acquisition.passive_sync_string, ...
            passive_sound_info);

    [passive_frames, ...
        passive_new_sound_st, ...
        passive_sounds_per_file] = ...
        binarize_passive_sounds( ...
            passive_sound_st, ...
            passive_sound_info, ...
            alignment_info);

    if ~isfolder(passive_info.save_path)
        mkdir(passive_info.save_path);
    end

    save( ...
        fullfile(passive_info.save_path, ...
        'alignment_variables.mat'), ...
        'passive_sound_info', ...
        'passive_sounds_per_file', ...
        'passive_sound_st', ...
        'passive_new_sound_st', ...
        'passive_sound_trials', ...
        'passive_sound_condition_array', ...
        'passive_frames', ...
        'conditions_per_speaker', ...
        'passive_info', ...
        '-v7.3');

    save( ...
        fullfile(passive_info.save_path, ...
        'passive_frames.mat'), ...
        'passive_frames', ...
        '-v7.3');



    passive_align_info.server = {config.server};
    passive_align_info.mouse_date = { ...
        fullfile(config.mouse, config.date)};

    [imaging_st, temp] = ...
        align_passive_imagingst_updated_noise( ...
            passive_align_info, ...
            passive_align_info.before_frames, ...
            passive_align_info.after_frames,config.experimenter);

    before_frames = passive_align_info.before_frames;
    after_frames =  passive_align_info.after_frames;
    save( ...
        fullfile(passive_info.save_path, ...
        'imaging_st.mat'), ...
        'imaging_st', ...
        'temp', ...
        'before_frames', ...
        'after_frames', ...
        '-v7.3');
end

%% ------------------------------------------------------------------------
% LOCAL FUNCTIONS
% -------------------------------------------------------------------------

function validate_configuration(config, info, sound_info)
    required_folders = {
        config.code_folder
        info.sync_base_path
        info.imaging_base_path
        info.processed_path
    };

    for i = 1:numel(required_folders)
        if ~isfolder(required_folders{i})
            error( ...
                'Alignment:MissingFolder', ...
                'Required folder not found: %s', ...
                required_folders{i});
        end
    end

    required_files = {
        config.condition_file
        fullfile(config.reward_model_dir, ...
            'mdl_pure_sol.mat')
        fullfile(config.reward_model_dir, ...
            'mdl_end_trial_sol.mat')
        fullfile(info.processed_path, ...
            'dff.mat')
        fullfile(info.processed_path, ...
            'deconv', ...
            'deconv.mat')
    };

    for i = 1:numel(required_files)
        if ~isfile(required_files{i})
            error( ...
                'Alignment:MissingFile', ...
                'Required file not found: %s', ...
                required_files{i});
        end
    end

    if info.galvo_channel == info.virmen_channel
        error( ...
            'Alignment:ChannelConflict', ...
            ['Galvo and ViRMEn channels cannot ' ...
             'use the same channel number.']);
    end

    if any(ismember( ...
            sound_info.spkr_channel_number, ...
            [info.galvo_channel, ...
             info.virmen_channel]))
        error( ...
            'Alignment:ChannelConflict', ...
            ['Speaker channels overlap with the ' ...
             'galvo or ViRMEn channel.']);
    end

    if numel(sound_info.spkr_channel_number) ...
            ~= numel(sound_info.speaker_ids)
        error( ...
            'Alignment:SpeakerMappingMismatch', ...
            ['The number of speaker channels must ' ...
             'match the number of speaker IDs.']);
    end
end

function [data, dataCell, source_name] = ...
        load_virmen_session(virmen_base)



    candidates = {
        [virmen_base, '_2.mat'], ...
        [virmen_base, '_Cell_2.mat'];
        [virmen_base, '_1.mat'], ...
        [virmen_base, '_Cell_1.mat'];
        [virmen_base, '.mat'], ...
        [virmen_base, '_Cell.mat']
    };

    for i = 1:size(candidates, 1)
        data_file = candidates{i, 1};
        cell_file = candidates{i, 2};

        if isfile(data_file) && isfile(cell_file)
            data = load(data_file);
            dataCell = load(cell_file);
            source_name = sprintf( ...
                '%s and %s', ...
                data_file, ...
                cell_file);
            return
        end
    end

    error( ...
        'Alignment:MissingVirmenFiles', ...
        ['No matching ViRMEn data/dataCell file pair ' ...
         'was found for base path: %s'], ...
        virmen_base);
end

function trial_info = build_trial_info( ...
        dataCell, ...
        is_stim_dataset)
%gets basic trialized data from virmen

    n_trials = numel(dataCell.dataCell);
    trial_info = repmat(struct(), 1, n_trials);

    for tr = 1:n_trials
        trial = dataCell.dataCell{1, tr};

        trial_info(tr).correct = ...
            trial.result.correct;

        trial_info(tr).condition = ...
            trial.maze.condition;

        if is_stim_dataset ...
                && isfield(trial.maze, ...
                'is_stim_trial')
            trial_info(tr).is_stim = ...
                trial.maze.is_stim_trial;
        end
    end
end

function sound_info = apply_task_sound_config( ...
        sound_info, ...
        task_sound, ...
        alignment_info)

    sound_info.sync_sampling_rate = ...
        alignment_info(1).sync_sampling_rate;

    fs = sound_info.sync_sampling_rate;

    sound_info.distance_between_sounds = ...
        task_sound.distance_between_sounds_sec * fs;

    sound_info.distance_within_sounds = ...
        task_sound.distance_within_sounds_sec * fs;

    sound_info.sound_duration = ...
        task_sound.sound_duration_sec * fs;

    sound_info.correct = ...
        task_sound.correct_iti_tone_sec;

    sound_info.incorrect = ...
        task_sound.incorrect_iti_tone_sec;

    sound_info.smoothing_factor = ...
        task_sound.smoothing_factor;

    sound_info.unique_detection_threshold = ...
        task_sound.unique_detection_threshold;

    sound_info.detection_threshold = ...
        task_sound.detection_threshold;

    sound_info.corrected_iti = ...
        task_sound.corrected_iti;

    sound_info.iti_tone_version = ...
        task_sound.iti_tone_version;
end

function sound_info = apply_passive_sound_config( ...
        sound_info, ...
        passive_sound, ...
        alignment_info, ...
        date_string)

    sound_info.sync_sampling_rate = ...
        alignment_info(1).sync_sampling_rate;

    fs = sound_info.sync_sampling_rate;

    sound_info.distance_between_sounds = ...
        passive_sound.distance_between_sounds_sec * fs;

    session_date = datetime( ...
        date_string, ...
        'InputFormat', ...
        'yyyy-MM-dd');

    if session_date < ...
            passive_sound.sensor_change_date
        distance_within_sec = ...
            passive_sound ...
            .distance_within_sounds_before_change_sec;
    else
        distance_within_sec = ...
            passive_sound ...
            .distance_within_sounds_after_change_sec;
    end

    sound_info.distance_within_sounds = ...
        distance_within_sec * fs;

    sound_info.sound_duration = ...
        passive_sound.sound_duration_sec * fs;

    sound_info.correct = [];
    sound_info.incorrect = [];

    sound_info.smoothing_factor = ...
        passive_sound.smoothing_factor;

    sound_info.unique_detection_threshold = ...
        passive_sound.unique_detection_threshold;

    sound_info.detection_threshold = ...
        passive_sound.detection_threshold;
end
