function [raw_velocity, corrected_velocity, qc] = ...
    run_velocity_alignment( ...
        alignment_info, ...
        calibration_info, ...
        sync_base_path, ...
        output_dir, ...
        plot_velocity_qc)
%RUN_VELOCITY_ALIGNMENT Extract, correct, validate, plot, and save velocity.
%
% Inputs
%   alignment_info   : Alignment structure containing frame_times and sync_id.
%   calibration_info : Calibration structure used by get_velocity and
%                      correct_velocity.
%   sync_base_path   : Folder containing synchronization files.
%   output_dir       : Folder where outputs should be saved.
%   plot_velocity_qc : Logical flag for plotting pitch, roll, and yaw.
%
% Outputs
%   raw_velocity       : 3 x total_frames uncorrected velocity array.
%   corrected_velocity : 3 x total_frames calibrated velocity array.
%   qc                 : Structure containing basic validation results.

if nargin < 5 || isempty(plot_velocity_qc)
    plot_velocity_qc = true;
end

if nargin < 4 || isempty(output_dir)
    error( ...
        'Alignment:MissingOutputDirectory', ...
        'An output directory must be provided.');
end

if isempty(alignment_info)
    error( ...
        'Alignment:MissingAlignmentInfo', ...
        'alignment_info is empty.');
end

if ~isstruct(calibration_info)
    error( ...
        'Alignment:InvalidCalibrationInfo', ...
        'calibration_info must be a structure.');
end

if ~isfolder(sync_base_path)
    error( ...
        'Alignment:MissingSyncDirectory', ...
        'Synchronization directory not found: %s', ...
        sync_base_path);
end

%% Extract and calibrate velocity
raw_velocity = get_velocity( ...
    alignment_info, ...
    calibration_info, ...
    sync_base_path);

corrected_velocity = correct_velocity( ...
    raw_velocity, ...
    calibration_info);

%% Validate output shape
if size(corrected_velocity, 1) ~= 3
    error( ...
        'Alignment:UnexpectedVelocityShape', ...
        ['Expected corrected_velocity to have three rows ' ...
         '(pitch, roll, yaw), but found %d.'], ...
        size(corrected_velocity, 1));
end

expected_total_frames = sum( ...
    arrayfun( ...
        @(x) numel(x.frame_times), ...
        alignment_info));

actual_total_frames = ...
    size(corrected_velocity, 2);

frame_count_matches = ...
    actual_total_frames == expected_total_frames;

if ~frame_count_matches
    warning( ...
        'Alignment:VelocityFrameMismatch', ...
        ['Velocity contains %d samples, but alignment_info ' ...
         'contains %d total frame times.'], ...
        actual_total_frames, ...
        expected_total_frames);
end

%% Record simple QC
qc.expected_total_frames = ...
    expected_total_frames;

qc.actual_total_frames = ...
    actual_total_frames;

qc.frame_count_matches = ...
    frame_count_matches;

qc.n_frames_with_missing_raw_velocity = ...
    nnz(any(isnan(raw_velocity), 1));

qc.n_frames_with_missing_corrected_velocity = ...
    nnz(any(isnan(corrected_velocity), 1));

%% Optional QC plot
if plot_velocity_qc
    figure;
    plot(corrected_velocity');
    xlabel('Imaging frame');
    ylabel('Corrected velocity');
    legend({'Pitch', 'Roll', 'Yaw'});
    title('Frame-aligned corrected ball velocity');
end

%% Save outputs
if ~isfolder(output_dir)
    mkdir(output_dir);
end

save( ...
    fullfile(output_dir, 'corrected_velocity.mat'), ...
    'corrected_velocity', ...
    'raw_velocity', ...
    'calibration_info', ...
    'qc', ...
    '-v7.3');

fprintf( ...
    ['Velocity processing complete: %d expected frames, ' ...
     '%d velocity samples, %d frames with missing corrected velocity.\n'], ...
    qc.expected_total_frames, ...
    qc.actual_total_frames, ...
    qc.n_frames_with_missing_corrected_velocity);
end
