if run_options.process_task
    mkdir(fullfile(processed_root, 'passive_corridor','/'))
    sound_info = apply_task_sound_config( ...
        sound_info, ...
        task_sound, ...
        alignment_info);

    sound_info.correct = [];
    sound_info.detection_threshold = 10;task_sound.smoothing_factor = 15;

    %process sound inputs
    [sound_st, sound_trials, sound_condition_array] = ...
        find_spkr_output_task_simple( ...
            info, ...
            alignment_info, ...
            'passive_01', ...
            sound_info, ...
            sound_info.iti_tone_version);

    trial_info = build_trial_info( ...
        dataCell, ...
        info.is_stim_dataset);

    %get virmen trial iterations
    digidata_its = get_digidata_iterations( ...
        info.sync_base_path, ...
        'passive_01', ...
        info.virmen_channel, ...
        alignment_info);

    %find positive peaks in virmen to use for alignment
    [virmen_it, trial_its, sound_condition_array] = ...
        get_virmen_iterations_and_times_digidata_positive_peaks_simple( ...
            info.sync_base_path, ...
            info.virmen_channel, ...
            'passive_01', ...
            sound_condition_array, ...
            data, ...
            alignment_info);

%     sound_st(1).file(15).spkr_loc = [1;2]
% sound_st(1).file(15).condition =3
% sound_st(1).file(15).true_condition =3
% 
% 
% sound_st(2).file(73).spkr_loc = [2;3]
% sound_st(2).file(73).condition =4
% sound_st(2).file(73).true_condition =4
% 
% sound_st(2).file(123).spkr_loc = [2;3]
% sound_st(2).file(123).condition =4
% sound_st(2).file(123).true_condition =4
% 
% sound_st(2).file(138).spkr_loc = [2;3]
% sound_st(2).file(138).condition =4
% sound_st(2).file(138).true_condition =4

    [passive_corridor_sound_frames, new_sound_st, sounds_per_file] = ...
        binarize_passive_sounds( ...
            sound_st, ...
            sound_info, ...
            alignment_info, ...
            'dir_string', ...
            'passive_01');

    % Reward-event detection is not enabled in this wrapper.
    reward_loc_pure_frames = [];

    %use all the data to create a imaging dictionary with trialized data
    imaging = align_virmen_data( ...
        dff, ...
        deconv, ...
        virmen_it, ...
        alignment_info, ...
        data, ...
        dataCell, ...
        trial_its, ...
        sounds_per_file, ...
        reward_loc_pure_frames);

    if run_options.plot_task_alignment_qc
        selected_fields = [1, 6, 7];
        plot_random_trials_alignment( ...
            imaging, ...
            selected_fields);
    end

    if ~isfolder(info.save_path)
        mkdir(fullfile(processed_root, 'passive_corridor','/'));
    end

    save( ...
        fullfile(fullfile(processed_root, 'passive_corridor','/'), ...
        'alignment_variables.mat'), ...
        'task_info', ...
        'sound_info', ...
        'sounds_per_file', ...
        'virmen_it', ...
        'sound_st', ...
        'new_sound_st', ...
        'sound_trials', ...
        'sound_condition_array', ...
        'reward_loc_pure_frames', ...
        'trial_its', ...
        'digidata_its', ...
        'trial_info', ...
        'info', ...
        '-v7.3');

    save( ...
        fullfile(fullfile(processed_root, 'passive_corridor','/'), 'imaging.mat'), ...
        'imaging', ...
        '-v7.3');

    save( ...
        fullfile(fullfile(processed_root, 'passive_corridor','/'), ...
        'passive_corridor_sound_frames.mat'), ...
        'passive_corridor_sound_frames', ...
        '-v7.3');

    passive_corridor_sound_frames_updated = ...
        fix_vr_sound_frames( ...
            passive_corridor_sound_frames, ...
            imaging, ...
            alignment_info);

    save( ...
        fullfile(info.save_path, ...
        'passive_corridor_sound_frames_updated.mat'), ...
        'passive_corridor_sound_frames_updated', ...
        '-v7.3');
end

%% ------------------------------------------------------------------------
% LOCAL FUNCTIONS
% -------------------------------------------------------------------------

function validate_configuration(config, info, sound_info)
    required_folders = {
        config.code_folder
        info.sync_base_path
        info.imaging_base_path
        info.processed_path
    };

    for i = 1:numel(required_folders)
        if ~isfolder(required_folders{i})
            error( ...
                'Alignment:MissingFolder', ...
                'Required folder not found: %s', ...
                required_folders{i});
        end
    end

    required_files = {
        config.condition_file
        fullfile(config.reward_model_dir, ...
            'mdl_pure_sol.mat')
        fullfile(config.reward_model_dir, ...
            'mdl_end_trial_sol.mat')
        fullfile(info.processed_path, ...
            'dff.mat')
        fullfile(info.processed_path, ...
            'deconv', ...
            'deconv.mat')
    };

    for i = 1:numel(required_files)
        if ~isfile(required_files{i})
            error( ...
                'Alignment:MissingFile', ...
                'Required file not found: %s', ...
                required_files{i});
        end
    end

    if info.galvo_channel == info.virmen_channel
        error( ...
            'Alignment:ChannelConflict', ...
            ['Galvo and ViRMEn channels cannot ' ...
             'use the same channel number.']);
    end

    if any(ismember( ...
            sound_info.spkr_channel_number, ...
            [info.galvo_channel, ...
             info.virmen_channel]))
        error( ...
            'Alignment:ChannelConflict', ...
            ['Speaker channels overlap with the ' ...
             'galvo or ViRMEn channel.']);
    end

    if numel(sound_info.spkr_channel_number) ...
            ~= numel(sound_info.speaker_ids)
        error( ...
            'Alignment:SpeakerMappingMismatch', ...
            ['The number of speaker channels must ' ...
             'match the number of speaker IDs.']);
    end
end

function [data, dataCell, source_name] = ...
        load_virmen_session(virmen_base)



    candidates = {
        [virmen_base, '_2.mat'], ...
        [virmen_base, '_Cell_2.mat'];
        [virmen_base, '_1.mat'], ...
        [virmen_base, '_Cell_1.mat'];
        [virmen_base, '.mat'], ...
        [virmen_base, '_Cell.mat']
    };

    for i = 1:size(candidates, 1)
        data_file = candidates{i, 1};
        cell_file = candidates{i, 2};

        if isfile(data_file) && isfile(cell_file)
            data = load(data_file);
            dataCell = load(cell_file);
            source_name = sprintf( ...
                '%s and %s', ...
                data_file, ...
                cell_file);
            return
        end
    end

    error( ...
        'Alignment:MissingVirmenFiles', ...
        ['No matching ViRMEn data/dataCell file pair ' ...
         'was found for base path: %s'], ...
        virmen_base);
end

function trial_info = build_trial_info( ...
        dataCell, ...
        is_stim_dataset)
%gets basic trialized data from virmen

    n_trials = numel(dataCell.dataCell);
    trial_info = repmat(struct(), 1, n_trials);

    for tr = 1:n_trials
        trial = dataCell.dataCell{1, tr};

        trial_info(tr).correct = ...
            trial.result.correct;

        trial_info(tr).condition = ...
            trial.maze.condition;

        if is_stim_dataset ...
                && isfield(trial.maze, ...
                'is_stim_trial')
            trial_info(tr).is_stim = ...
                trial.maze.is_stim_trial;
        end
    end
end

function sound_info = apply_task_sound_config( ...
        sound_info, ...
        task_sound, ...
        alignment_info)

    sound_info.sync_sampling_rate = ...
        alignment_info(1).sync_sampling_rate;

    fs = sound_info.sync_sampling_rate;

    sound_info.distance_between_sounds = ...
        task_sound.distance_between_sounds_sec * fs;

    sound_info.distance_within_sounds = ...
        task_sound.distance_within_sounds_sec * fs;

    sound_info.sound_duration = ...
        task_sound.sound_duration_sec * fs;

    sound_info.correct = ...
        task_sound.correct_iti_tone_sec;

    sound_info.incorrect = ...
        task_sound.incorrect_iti_tone_sec;

    sound_info.smoothing_factor = ...
        task_sound.smoothing_factor;

    sound_info.unique_detection_threshold = ...
        task_sound.unique_detection_threshold;

    sound_info.detection_threshold = ...
        task_sound.detection_threshold;

    sound_info.corrected_iti = ...
        task_sound.corrected_iti;

    sound_info.iti_tone_version = ...
        task_sound.iti_tone_version;
end

function sound_info = apply_passive_sound_config( ...
        sound_info, ...
        passive_sound, ...
        alignment_info, ...
        date_string)

    sound_info.sync_sampling_rate = ...
        alignment_info(1).sync_sampling_rate;

    fs = sound_info.sync_sampling_rate;

    sound_info.distance_between_sounds = ...
        passive_sound.distance_between_sounds_sec * fs;

    session_date = datetime( ...
        date_string, ...
        'InputFormat', ...
        'yyyy-MM-dd');

    if session_date < ...
            passive_sound.sensor_change_date
        distance_within_sec = ...
            passive_sound ...
            .distance_within_sounds_before_change_sec;
    else
        distance_within_sec = ...
            passive_sound ...
            .distance_within_sounds_after_change_sec;
    end

    sound_info.distance_within_sounds = ...
        distance_within_sec * fs;

    sound_info.sound_duration = ...
        passive_sound.sound_duration_sec * fs;

    sound_info.correct = [];
    sound_info.incorrect = [];

    sound_info.smoothing_factor = ...
        passive_sound.smoothing_factor;

    sound_info.unique_detection_threshold = ...
        passive_sound.unique_detection_threshold;

    sound_info.detection_threshold = ...
        passive_sound.detection_threshold;
end
